# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-intersystems_iris_guardium_filter_jars"
require "java"

class LogStash::Filters::IntersystemsIRISGuardiumFilter < LogStash::Filters::Base
  config_name "intersystems_iris_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.intersystemsiris.IntersystemsIRISGuardiumFilter.java_class; end
end
