# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-yugabytedb_guardium_filter_jars"
require "java"

class LogStash::Filters::YugabytedbGuardiumFilter < LogStash::Filters::Base
  config_name "yugabytedb_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.yugabytedb.YugabytedbGuardiumFilter.java_class; end
end
