# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8

require 'jar_dependencies'
require_jar('com.ibm.guardium.auroramysql', 'logstash-filter-awsAuroraMysql_guardium_plugin_filter', '1.0.1')
