/*

Copyright IBM Corp. 2021, 2022 All rights reserved.
SPDX-License-Identifier: Apache-2.0

*/
package com.ibm.guardium.firestore;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.Collection;
import java.util.Collections;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.Test;
import org.logstash.Event;
import org.logstash.plugins.ConfigurationImpl;
import org.logstash.plugins.ContextImpl;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import co.elastic.logstash.api.Configuration;
import co.elastic.logstash.api.Context;
import co.elastic.logstash.api.FilterMatchListener;
import co.elastic.logstash.api.PluginConfigSpec;

public class FireStoreFilterConnectorTest {

	@Test
	public void configSchemaTest() {
		final String gcpString2 = "";
		FireStoreGuardiumFilter filter = getFireStoreFilterConnector(gcpString2);
		Collection<PluginConfigSpec<?>> events = filter.configSchema();
		assertNotNull(events);
	}

	@Test
	public void commonUtilsTest() {
		CommonUtils commonUtils = new CommonUtils();
		assertNotNull(commonUtils);
	}

	@Test
	public void getIdTest() {
		final String gcpString2 = "";
		FireStoreGuardiumFilter filter = getFireStoreFilterConnector(gcpString2);
		String id = filter.getId();
		assertNotNull(id);
	}
//query
	@Test
	public void filterEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"collectionId\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);

	}
	@Test
	public void filterEventTest1() {
		String gcpString2="{ \"protoPayload\": { \"@type\": \"type.googleapis.com/google.cloud.audit.AuditLog\", \"status\": {}, \"authenticationInfo\": { \"principalEmail\": \"service-1065340084898@firebase-rules.iam.gserviceaccount.com\" }, \"requestMetadata\": { \"callerIp\": \"110.235.238.57\", \"callerSuppliedUserAgent\": \"grpc-java-netty/1.45.0,gzip(gfe)\", \"requestAttributes\": { \"time\": \"2022-05-31T06:12:22.732516Z\", \"auth\": {} }, \"destinationAttributes\": {} }, \"serviceName\": \"firestore.googleapis.com\", \"methodName\": \"google.firestore.v1.Firestore.RunQuery\", \"authorizationInfo\": [ { \"resource\": \"projects/project-sccd/databases/\", \"permission\": \"datastore.entities.get\", \"granted\": true, \"resourceAttributes\": {} }, { \"resource\": \"projects/project-sccd/databases/\", \"permission\": \"datastore.entities.list\", \"granted\": true, \"resourceAttributes\": {} } ], \"resourceName\": \"projects/project-sccd/databases/(default)\", \"numResponseItems\": \"3\", \"request\": { \"@type\": \"type.googleapis.com/google.firestore.v1.RunQueryRequest\", \"structuredQuery\": { \"where\": { \"fieldFilter\": { \"field\": { \"fieldPath\": \"AGC\" }, \"value\": { \"stringValue\": \"Agra Cantonment\" }, \"op\": \"EQUAL\" } }, \"from\": [ { \"collectionId\": \"hclQAtest\" } ] }, \"parent\": \"projects/project-sccd/databases/(default)/documents\" }, \"metadata\": { \"processingDuration\": \"0.095206456s\", \"@type\": \"type.googleapis.com/google.cloud.audit.DatastoreServiceData\" } }, \"insertId\": \"-1nik91d38rs\", \"resource\": { \"type\": \"audited_resource\", \"labels\": { \"project_id\": \"project-sccd\", \"service\": \"firestore.googleapis.com\", \"method\": \"google.firestore.v1.Firestore.RunQuery\" } }, \"timestamp\": \"2022-05-31T06:12:22.639073Z\", \"severity\": \"INFO\", \"logName\": \"projects/project-sccd/logs/cloudaudit.googleapis.com%2Fdata_access\", \"receiveTimestamp\": \"2022-05-31T06:12:23.245972645Z\" }";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);

	}
	@Test
	public void filterDeleteTest() {
		final String gcpString2="{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"service-1065340084898@firebase-rules.iam.gserviceaccount.com\"},\"requestMetadata\":{\"callerIp\":\"110.235.238.189\",\"callerSuppliedUserAgent\":\"grpc-java-netty\\/1.44.1,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-30T10:55:50.753852Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Commit\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.delete\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.CommitRequest\",\"writes\":[{\"delete\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/hclQAtest\\/Automation1653905374173\\/collection2\\/document2\"}],\"database\":\"projects\\/project-sccd\\/databases\\/(default)\"},\"metadata\":{\"processingDuration\":\"0.025153360s\",\"keys\":[\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/hclQAtest\\/Automation1653905374173\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-8vhk9ve2j5pm\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Commit\",\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-05-30T10:55:50.728585Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-30T10:55:51.059073708Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterClientipv6Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"2345:0425:2CA1:0000:0000:0567:5673:23b5\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:19:25.155013Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Write\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":[{\"update\":{}}],\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"8lyqx4dc842\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Write\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:19:25.128427Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-07T18:19:25.245480530Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterUpdateField() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"authenticationInfo\":{\"principalEmail\":\"vejalla.indrani@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"117.216.244.14\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/103.0.0.0 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-07-27T13:28:56.286550Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.admin.v1.FirestoreAdmin.UpdateField\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/collection%2027%20jul\\/fields\\/id\",\"permission\":\"datastore.indexes.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/collection-27-jul\\/fields\\/id\",\"request\":{\"field\":{\"name\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/collection%2027%20jul\\/fields\\/id\"},\"@type\":\"type.googleapis.com\\/google.firestore.admin.v1.UpdateFieldRequest\",\"updateMask\":\"indexConfig\"}},\"insertId\":\"1ndnjwjc1us\",\"resource\":{\"type\":\"datastore_database\",\"labels\":{\"project_id\":\"project-sccd\",\"database_id\":\"(default)\"}},\"timestamp\":\"2022-07-27T13:28:56.128944Z\",\"severity\":\"NOTICE\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Factivity\",\"operation\":{\"id\":\"projects\\/project-sccd\\/databases\\/(default)\\/operations\\/AyBhOTVjZGVmNDI3N2UtYmY3YS00ZDI0LTllYWUtYWZlMjYxZWIkGnRsdWFmZWQHEjFzLXNhLXJleGVkbmktbmltZGETCkYS\",\"producer\":\"firestore.googleapis.com\",\"first\":true},\"receiveTimestamp\":\"2022-07-27T13:28:56.343770152Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterListDocumentTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"balram.verma@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.184.206\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/103.0.5060.134 Safari\\/537.36 Edg\\/103.0.1264.77,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-08-02T11:06:33.091049Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.ListDocuments\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"numResponseItems\":\"2\",\"request\":{\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\",\"collectionId\":\"1-june-collection\",\"pageSize\":300,\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListDocumentsRequest\",\"showMissing\":true,\"mask\":{\"fieldPaths\":[\"_none_\"]}},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"processingDuration\":\"0.025394424s\"}},\"insertId\":\"9fsyfze155de\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.ListDocuments\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"project-sccd\"}},\"timestamp\":\"2022-08-02T11:06:33.067346Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-08-02T11:06:33.343963963Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterListDocumentTest1() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"balram.verma@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.184.206\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/103.0.5060.134 Safari\\/537.36 Edg\\/103.0.1264.77,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-08-02T11:06:33.542419Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.ListDocuments\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\",\"pageSize\":300,\"orderBy\":\"june\",\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListDocumentsRequest\",\"collectionId\":\"21-june-collection\",\"mask\":{\"fieldPaths\":[\"june\"]}},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"processingDuration\":\"0.026778640s\"}},\"insertId\":\"7rsi71e16cl8\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"method\":\"google.firestore.v1.Firestore.ListDocuments\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-08-02T11:06:33.518048Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-08-02T11:06:33.989218701Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterListDocumentTestFirefoo() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"aayushi.palod@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"103.167.194.122\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.17 Chrome\\/96.0.4664.110 Electron\\/16.0.7 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-08-02T10:29:07.963204Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.ListDocuments\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"numResponseItems\":\"1\",\"request\":{\"showMissing\":true,\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListDocumentsRequest\",\"pageSize\":50,\"collectionId\":\"3MAYCOLLECTION\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"processingDuration\":\"0.007463104s\"}},\"insertId\":\"-qwutq2dssmk\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.ListDocuments\"}},\"timestamp\":\"2022-08-02T10:29:07.955852Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-08-02T10:29:08.702028863Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterCreateIndex() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"authenticationInfo\":{\"principalEmail\":\"balram.verma@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"122.161.51.105\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/102.0.5005.124 Safari\\/537.36 Edg\\/102.0.1245.44,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-06-22T06:28:58.561069Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.admin.v1.FirestoreAdmin.CreateIndex\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\",\"permission\":\"datastore.indexes.create\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\",\"request\":{\"index\":{\"queryScope\":\"COLLECTION\",\"fields\":[{\"fieldPath\":\"name\",\"order\":\"ASCENDING\"},{\"order\":\"ASCENDING\",\"fieldPath\":\"address\"}],\"name\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\\/indexes\\/\"},\"@type\":\"type.googleapis.com\\/google.firestore.admin.v1.CreateIndexRequest\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\"}},\"insertId\":\"17auw38bct\",\"resource\":{\"type\":\"datastore_index\",\"labels\":{\"project_id\":\"project-sccd\",\"database_id\":\"(default)\",\"index_id\":\"CICAgLiIkYMK\"}},\"timestamp\":\"2022-06-22T06:28:57.753647Z\",\"severity\":\"NOTICE\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Factivity\",\"operation\":{\"id\":\"projects\\/project-sccd\\/databases\\/(default)\\/operations\\/AyBlYjZhOTFmYmYzNzgtOTI2OC1iN2E0LTI3OGMtODQzNDFiM2MkGnRsdWFmZWQHEjFzLXNhLXJleGVkbmktbmltZGETCkYS\",\"producer\":\"firestore.googleapis.com\",\"first\":true},\"receiveTimestamp\":\"2022-06-22T06:28:58.618236560Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterDeleteIndex() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"authenticationInfo\":{\"principalEmail\":\"aayushi.palod@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"122.161.51.105\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/102.0.5005.124 Safari\\/537.36 Edg\\/102.0.1245.44,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-06-22T07:11:09.274182Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.admin.v1.FirestoreAdmin.DeleteIndex\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\\/indexes\\/CICAgLiIkYMK\",\"permission\":\"datastore.indexes.delete\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\\/indexes\\/CICAgLiIkYMK\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.admin.v1.DeleteIndexRequest\",\"name\":\"projects\\/project-sccd\\/databases\\/(default)\\/collectionGroups\\/09march-coll\\/indexes\\/CICAgLiIkYMK\"}},\"insertId\":\"1iy4kipbco\",\"resource\":{\"type\":\"datastore_index\",\"labels\":{\"database_id\":\"(default)\",\"index_id\":\"CICAgLiIkYMK\",\"project_id\":\"project-sccd\"}},\"timestamp\":\"2022-06-22T07:11:09.064713Z\",\"severity\":\"NOTICE\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Factivity\",\"receiveTimestamp\":\"2022-06-22T07:11:09.582401147Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	
	//single document
	@Test
	public void filterListDocumentTest3() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"service-1065340084898@firebase-rules.iam.gserviceaccount.com\"},\"requestMetadata\":{\"callerIp\":\"110.235.238.189\",\"callerSuppliedUserAgent\":\"grpc-java-netty\\/1.44.1,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-30T08:37:02.038215Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.BatchGetDocuments\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"numResponseItems\":\"1\",\"request\":{\"documents\":[\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/hclQAtest\\/demo\"],\"database\":\"projects\\/project-sccd\\/databases\\/(default)\",\"@type\":\"type.googleapis.com\\/google.firestore.v1.BatchGetDocumentsRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/hclQAtest\\/demo\"],\"processingDuration\":\"0.090037640s\"}},\"insertId\":\"vd0grre25azw\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.BatchGetDocuments\"}},\"timestamp\":\"2022-05-30T08:37:01.949990Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-30T08:37:02.389601335Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}
	@Test
	public void filterQueryEventTest() {
		final String gcpString2 = "";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterNullAddTargetQueryEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:27:41.029461Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-tyqlsme25kiw\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\",\"method\":\"google.firestore.v1.Firestore.Listen\"}},\"timestamp\":\"2022-02-07T18:27:41.019361Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:27:41.589200051Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterNullStructuredQueryQueryEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:27:41.029461Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\",\"addTarget\":{\"query\":{},\"targetId\":50}},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-tyqlsme25kiw\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\",\"method\":\"google.firestore.v1.Firestore.Listen\"}},\"timestamp\":\"2022-02-07T18:27:41.019361Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:27:41.589200051Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterNullRequestEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:27:41.029461Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-tyqlsme25kiw\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\",\"method\":\"google.firestore.v1.Firestore.Listen\"}},\"timestamp\":\"2022-02-07T18:27:41.019361Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:27:41.589200051Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterDocumentQueryEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:25:11.774909Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"documents\":{\"documents\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]},\"targetId\":48},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"mh87v7ddl2m\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:25:11.765604Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"61bdc7de-2f77-41e9-a75d-bde29f45b9f9\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:25:12.570513674Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterWriteQueryEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:19:25.155013Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Write\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":[{\"update\":{\"name\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"}}],\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"8lyqx4dc842\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Write\",\"project_id\":\"guarduim\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-02-07T18:19:25.128427Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-07T18:19:25.245480530Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterWriteQuery1EventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:19:25.155013Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Write\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":[],\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"8lyqx4dc842\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Write\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:19:25.128427Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-07T18:19:25.245480530Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterMaskQueryEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"anandku@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.188.118\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/98.0.4758.80 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-14T13:59:27.025970Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.ListDocuments\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"numResponseItems\":\"3\",\"request\":{\"showMissing\":true,\"pageSize\":300,\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListDocumentsRequest\",\"collectionId\":\"Anu-Feb02-22\",\"mask\":{\"fieldPaths\":[\"_none_\"]},\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-jj88odetw4\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"project_id\":\"project-sccd\",\"method\":\"google.firestore.v1.Firestore.ListDocuments\"}},\"timestamp\":\"2022-02-14T13:59:27.007324Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-14T13:59:27.620380979Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterInvalidJsonEventTest() {
		final String gcpString2 = "{\"protoPayload\":\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"collectionId\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterNotFireStoreDBJsonEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore123.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"collectionId\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore123.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore123.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterErrorJsonEventTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{\"code\":1},\"authenticationInfo\":{\"principalEmail\":\"anubhav.kumar@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.187.116\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36 Edg\\/97.0.1072.69,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-08T15:32:46.433832Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\",\"addTarget\":{\"targetId\":10,\"query\":{\"structuredQuery\":{\"orderBy\":[{\"direction\":\"ASCENDING\",\"field\":{\"fieldPath\":\"__name__\"}}],\"from\":[{\"collectionId\":\"Feb012022\"}]},\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"}}},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-9pka6kd65w0\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Listen\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"project-sccd\"}},\"timestamp\":\"2022-02-08T15:32:46.422658Z\",\"severity\":\"ERROR\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"2e6d0077-a3ae-4cff-ac46-630eb1288175\",\"producer\":\"firestore.googleapis.com\",\"last\":true},\"receiveTimestamp\":\"2022-02-08T15:32:46.759519288Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterOperationTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"anubhav.kumar@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.187.116\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36 Edg\\/97.0.1072.69,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-08T17:55:31.244823Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\",\"addTarget\":{\"documents\":{\"documents\":[\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/Feb012022\\/1140am\"]},\"targetId\":24}},\"metadata\":{\"keys\":[\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/Feb012022\\/1140am\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"x0uag6dryui\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-02-08T17:55:31.236968Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"7759028e-0fd4-469d-9a6c-e85fd5be7747\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-08T17:55:31.346346757Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterHttpTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"collectionId\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventQuery1Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventQuery2Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventQuery3Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventDocument1Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:32.381043Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"targetId\":48,\"documents\":{}},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"mhegnldfj2a\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-02-07T18:22:32.379206Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"61bdc7de-2f77-41e9-a75d-bde29f45b9f9\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:33.184020050Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventDocument2Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:32.381043Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"targetId\":48,\"documents\":{\"documents\":[]}},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"mhegnldfj2a\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-02-07T18:22:32.379206Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"61bdc7de-2f77-41e9-a75d-bde29f45b9f9\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:33.184020050Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventException1Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:32.381043Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"targetId\":48,\"documents\":{\"documents\":[]}},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"mhegnldfj2a\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-02-07T18:22:32.379206Z\",\"severity\":\"ERROR\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"61bdc7de-2f77-41e9-a75d-bde29f45b9f9\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:33.184020050Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventProjectId1Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:32.381043Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"targetId\":48,\"documents\":{\"documents\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"mhegnldfj2a\",\"resource\":{},\"timestamp\":\"2022-02-07T18:22:32.379206Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"61bdc7de-2f77-41e9-a75d-bde29f45b9f9\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:33.184020050Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventProjectId2Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:32.381043Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"targetId\":48,\"documents\":{\"documents\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"mhegnldfj2a\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Listen\",\"service\":\"firestore.googleapis.com\"}},\"timestamp\":\"2022-02-07T18:22:32.379206Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"61bdc7de-2f77-41e9-a75d-bde29f45b9f9\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:33.184020050Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventWrite1Test() {
		// final String gcpString2 =
		// "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0
		// (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko)
		// Chrome\\/97.0.4692.99
		// Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:19:25.155013Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Write\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":{\"update\":{\"name\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"}},\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"8lyqx4dc842\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Write\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:19:25.128427Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-07T18:19:25.245480530Z\"}";
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"meenakshi_b@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"223.233.77.26\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.4 Chrome\\/94.0.4606.81 Electron\\/15.3.4 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-02T06:39:02.996977Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"numResponseItems\":\"1\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":[{\"update\":{\"name\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"}}],\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-qwv2dpe72di2\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\",\"project_id\":\"project-sccd\"}},\"timestamp\":\"2022-05-02T06:39:02.938121Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-02T06:39:03.432120852Z\"}";

		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventQueryCheck1Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventQueryCheck2Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"abc\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventWrite2Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:19:25.155013Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Write\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":[{\"update\":{}}],\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"8lyqx4dc842\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Write\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:19:25.128427Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-07T18:19:25.245480530Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterEventWrite3Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:19:25.155013Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Write\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.WriteRequest\",\"writes\":null,\"database\":\"projects\\/guarduim\\/databases\\/(default)\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\",\"keys\":[\"projects\\/guarduim\\/databases\\/(default)\\/documents\\/collection55\\/document55\"]}},\"insertId\":\"8lyqx4dc842\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"method\":\"google.firestore.v1.Firestore.Write\",\"service\":\"firestore.googleapis.com\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:19:25.128427Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-02-07T18:19:25.245480530Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterVerb1Test() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"abc\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"httpRequest\":{\"serverIp\":\"163.53.85.108\"},\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void filterObjectWritesCollectionTest() {
		final String gcpString2 = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"meenakshi_b@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"223.233.77.26\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.4 Chrome\\/94.0.4606.81 Electron\\/15.3.4 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-02T06:39:03.212715Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"writes\":[{\"collectionId\":\"cid1\"}],\"@type\":\"type.googleapis.com\\/google.firestore.v1.RunQueryRequest\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-7rnbxue5nseg\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\"}},\"timestamp\":\"2022-05-02T06:39:03.122415Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-02T06:39:03.478563002Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString2);
		assertNotNull(events);
	}

	@Test
	public void validateKey() throws Exception {
		final String fireStoreLogsString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"brijeshyadav1979@gmail.com\"},\"requestMetadata\":{\"callerIp\":\"163.53.85.108\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/97.0.4692.99 Safari\\/537.36,gzip(gfe),gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-02-07T18:22:40.885763Z\",\"reason\":\"8uSywAYxWi9GaXJlc3RvcmUgd2F0Y2ggZm9yIGxvbmcgcnVubmluZyBzdHJlYW1pbmcgcnBjLg\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Listen\",\"authorizationInfo\":[{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/guarduim\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/guarduim\\/databases\\/(default)\",\"request\":{\"addTarget\":{\"query\":{\"parent\":\"projects\\/guarduim\\/databases\\/(default)\\/documents\",\"structuredQuery\":{\"from\":[{\"collectionId\":\"collection55\"}],\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"},\"direction\":\"ASCENDING\"}]}},\"targetId\":50},\"@type\":\"type.googleapis.com\\/google.firestore.v1.ListenRequest\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-4flla8df63i\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Listen\",\"project_id\":\"guarduim\"}},\"timestamp\":\"2022-02-07T18:22:40.874854Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/guarduim\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"operation\":{\"id\":\"381d996b-ef01-4267-bbb3-0b13c7b2cdc1\",\"producer\":\"firestore.googleapis.com\"},\"receiveTimestamp\":\"2022-02-07T18:22:41.231100438Z\"}";
		final JsonObject spannerJson = JsonParser.parseString(fireStoreLogsString).getAsJsonObject();
		JsonObject record = Parser.validateKeyExistance(spannerJson, "databaseName");
		assertNotNull(record);
	}

	@Test
	public void testServicePrinciple() {
		final String fireStoreLogsString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"service-1065340084898@firebase-rules.iam.gserviceaccount.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.184.131\",\"callerSuppliedUserAgent\":\"grpc-java-netty\\/1.41.0,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-04-29T13:12:25.102291Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.Commit\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.create\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.update\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"writes\":[{\"update\":{\"name\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/aa-27-apr-coll\\/29-04_Doc1\"}}],\"database\":\"projects\\/project-sccd\\/databases\\/(default)\",\"@type\":\"type.googleapis.com\\/google.firestore.v1.CommitRequest\"},\"metadata\":{\"keys\":[\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/aa-27-apr-coll\\/29-04_Doc1\"],\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-9yck8e22066\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.Commit\",\"project_id\":\"project-sccd\"}},\"timestamp\":\"2022-04-29T13:12:24.987036Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-04-29T13:12:25.516222763Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(fireStoreLogsString);
		assertNotNull(events);
	}

	@Test
	public void test1ThridPartData() {
		final String fireStoreLogsString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"meenakshi_b@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"223.233.77.26\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.4 Chrome\\/94.0.4606.81 Electron\\/15.3.4 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-02T06:39:03.212715Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"structuredQuery\":{\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"}}],\"startAt\":{\"values\":[{\"referenceValue\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/Googleconsole2\\/Doc2\"}]},\"limit\":49,\"where\":{\"fieldFilter\":{\"value\":{\"stringValue\":\"firestore topic\"},\"field\":{\"fieldPath\":\"Title\"},\"op\":\"EQUAL\"}},\"from\":[{\"collectionId\":\"Googleconsole2\"}]},\"@type\":\"type.googleapis.com\\/google.firestore.v1.RunQueryRequest\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-7rnbxue5nseg\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\"}},\"timestamp\":\"2022-05-02T06:39:03.122415Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-02T06:39:03.478563002Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(fireStoreLogsString);
		assertNotNull(events);
	}

	@Test
	public void test2ThridPartData() {
		final String fireStoreLogsString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"meenakshi_b@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"223.233.77.26\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.4 Chrome\\/94.0.4606.81 Electron\\/15.3.4 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-02T06:39:03.212715Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"structuredQuery\":{\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"}}],\"startAt\":{\"values\":[{\"referenceValue\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/Googleconsole2\\/Doc2\"}]},\"limit\":49,\"where\":{\"fieldFilter\":{\"value\":{\"stringValue\":\"firestore topic\"},\"field\":{\"fieldPath\":\"Title\"},\"op\":\"EQUAL\"}}},\"@type\":\"type.googleapis.com\\/google.firestore.v1.RunQueryRequest\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-7rnbxue5nseg\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\"}},\"timestamp\":\"2022-05-02T06:39:03.122415Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-02T06:39:03.478563002Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(fireStoreLogsString);
		assertNotNull(events);
	}

	@Test
	public void test3ThridPartData() {
		final String fireStoreLogsString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"meenakshi_b@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"223.233.77.26\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.4 Chrome\\/94.0.4606.81 Electron\\/15.3.4 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-02T06:39:03.212715Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"structuredQuery\":{\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"}}],\"startAt\":{\"values\":[{\"referenceValue\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/Googleconsole2\\/Doc2\"}]},\"limit\":49,\"where\":{\"fieldFilter\":{\"value\":{\"stringValue\":\"firestore topic\"},\"field\":{\"fieldPath\":\"Title\"},\"op\":\"EQUAL\"}},\"from\":[{\"abc\":\"Googleconsole2\"}]},\"@type\":\"type.googleapis.com\\/google.firestore.v1.RunQueryRequest\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-7rnbxue5nseg\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\"}},\"timestamp\":\"2022-05-02T06:39:03.122415Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-02T06:39:03.478563002Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(fireStoreLogsString);
		assertNotNull(events);
	}

	@Test
	public void test4ThridPartData() {
		final String fireStoreLogsString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"meenakshi_b@hcl.com\"},\"requestMetadata\":{\"callerIp\":\"223.233.77.26\",\"callerSuppliedUserAgent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Firefoo\\/1.3.4 Chrome\\/94.0.4606.81 Electron\\/15.3.4 Safari\\/537.36,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-02T06:39:03.212715Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"structuredQuery\":{\"orderBy\":[{\"field\":{\"fieldPath\":\"__name__\"}}],\"startAt\":{\"values\":[{\"referenceValue\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\\/Googleconsole2\\/Doc2\"}]},\"limit\":49,\"where\":{\"fieldFilter\":{\"value\":{\"stringValue\":\"firestore topic\"},\"field\":{\"fieldPath\":\"Title\"},\"op\":\"EQUAL\"}},\"from\":[]},\"@type\":\"type.googleapis.com\\/google.firestore.v1.RunQueryRequest\",\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-7rnbxue5nseg\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\"}},\"timestamp\":\"2022-05-02T06:39:03.122415Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-02T06:39:03.478563002Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(fireStoreLogsString);
		assertNotNull(events);
	}

	@Test
	public void filterQueryEventTestMaskRedacted() {
		final String gcpString = "{\"protoPayload\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.AuditLog\",\"status\":{},\"authenticationInfo\":{\"principalEmail\":\"service-1065340084898@firebase-rules.iam.gserviceaccount.com\"},\"requestMetadata\":{\"callerIp\":\"168.149.184.202\",\"callerSuppliedUserAgent\":\"grpc-java-netty\\/1.41.0,gzip(gfe)\",\"requestAttributes\":{\"time\":\"2022-05-04T12:15:14.293925Z\",\"auth\":{}},\"destinationAttributes\":{}},\"serviceName\":\"firestore.googleapis.com\",\"methodName\":\"google.firestore.v1.Firestore.RunQuery\",\"authorizationInfo\":[{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.get\",\"granted\":true,\"resourceAttributes\":{}},{\"resource\":\"projects\\/project-sccd\\/databases\\/\",\"permission\":\"datastore.entities.list\",\"granted\":true,\"resourceAttributes\":{}}],\"resourceName\":\"projects\\/project-sccd\\/databases\\/(default)\",\"request\":{\"@type\":\"type.googleapis.com\\/google.firestore.v1.RunQueryRequest\",\"structuredQuery\":{\"where\":{\"compositeFilter\":{\"filters\":[{\"fieldFilter\":{\"value\":{\"integerValue\":\"1\"},\"field\":{\"fieldPath\":\"`Page nummber`\"},\"op\":\"GREATER_THAN\"}},{\"fieldFilter\":{\"value\":{\"stringValue\":\"Demo\"},\"field\":{\"fieldPath\":\"title\"},\"op\":\"EQUAL\"}},{\"fieldFilter\":{\"value\":{\"stringValue\":\"paragraphs\"},\"op\":\"EQUAL\",\"field\":{\"fieldPath\":\"Body\"}}}],\"op\":\"AND\"}},\"from\":[{\"collectionId\":\"22Apr_TestQA1\"}]},\"parent\":\"projects\\/project-sccd\\/databases\\/(default)\\/documents\"},\"metadata\":{\"@type\":\"type.googleapis.com\\/google.cloud.audit.DatastoreServiceData\"}},\"insertId\":\"-31qo8kd6tui\",\"resource\":{\"type\":\"audited_resource\",\"labels\":{\"project_id\":\"project-sccd\",\"service\":\"firestore.googleapis.com\",\"method\":\"google.firestore.v1.Firestore.RunQuery\"}},\"timestamp\":\"2022-05-04T12:15:14.193517Z\",\"severity\":\"INFO\",\"logName\":\"projects\\/project-sccd\\/logs\\/cloudaudit.googleapis.com%2Fdata_access\",\"receiveTimestamp\":\"2022-05-04T12:15:14.710136615Z\"}";
		Collection<co.elastic.logstash.api.Event> events = getEvents(gcpString);
		assertNotNull(events);
	}
	private FireStoreGuardiumFilter getFireStoreFilterConnector(String jsonString) {
		Configuration config = new ConfigurationImpl(Collections.singletonMap("source", jsonString));
		Context context = new ContextImpl(null, null);
		FireStoreGuardiumFilter filter = new FireStoreGuardiumFilter("spn-id", config, context);
		return filter;
	}

	public Collection<co.elastic.logstash.api.Event> getEvents(String gcpStringRequest) {
		FireStoreGuardiumFilter filter = getFireStoreFilterConnector(gcpStringRequest);
		Event e = new org.logstash.Event();
		TestMatchListener matchListener = new TestMatchListener();
		e.setField("message", gcpStringRequest);
		Collection<co.elastic.logstash.api.Event> events = filter.filter(Collections.singletonList(e), matchListener);
		return events;
	}

}

class TestMatchListener implements FilterMatchListener {
	private AtomicInteger matchCount = new AtomicInteger(0);

	public int getMatchCount() {
		return matchCount.get();
	}

	@Override
	public void filterMatched(co.elastic.logstash.api.Event arg0) {
		matchCount.incrementAndGet();

	}
}
