filter {
	if [type] == "profile_name" and "param_datasource_tag" in [tags] {

        mutate {
            split => { "message" => "," }
        }

        if [message][0] == "0" or [message][1] == "C" or [message][7] == "" or [message][7] == "distributed" or [message][8] == "[unknown]" {
            drop { }
        }

        mutate {
            remove_tag => ["beats_input_codec_plain_applied"]
            join => { "message" => "," }
            add_field => { "serverIP" => "%{[host][ip][0]}" }
            add_field => { "serverHostname" => "%{[host][name]}" }
        }

        singlestoredb_guardium_filter{}
	}
}