# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-***REMOVED***phana_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::SapHanaGuardiumPluginFilter < LogStash::Filters::Base
  config_name "***REMOVED***phana_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.***REMOVED***phana.SapHanaGuardiumPluginFilter.java_class; end
end
