language: shell

os:
  - linux

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

before_script:
  - chmod -R 777 .

script:
  - chmod -R 755 ./build
  - ./build/buildUCDefaultOfflinePackage.sh
  - ./build/test.sh