language: shell

os:
  - linux

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
  - chmod -R 777 .

stages:
  - name: Build
  - name: Test

jobs:
  include:
    - stage: Build
      name: "Update plugins and prepare UC default offline package"
      script:
        - ./build/buildUCDefaultOfflinePackage.sh

    - stage: Test
      name: "Run tests"
      script:
        - ./build/test.sh
