language: shell

os:
  - linux

before_script:
  - chmod -R 777 .
  - sudo apt-get update && sudo apt-get install -y parallel  # Install GNU parallel if needed

script:
  - chmod -R 755 ./build
  - travis_wait 80 ./build/buildUCDefaultOfflinePackage.sh  # Increase timeout to 80 minutes
  - ./build/test.sh