language: java

os:
  - linux

# Define stages to run jobs in parallel
stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: "Build UC Default Offline Package"
      script:
        - ./build/buildUCDefaultOfflinePackage.sh

    - stage: test
      name: "Run Tests"
      script:
        - ./build/test.sh

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
