# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8

require 'jar_dependencies'
require_jar('com.infoinsightsllc.guardium', 'logstash-filter-guardium_snowflake_filter', '1.0.0')
