# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-opensearch_guardium_filter_jars"
require "java"

class LogStash::Filters::OpensearchGuardiumFilter < LogStash::Filters::Base
  config_name "opensearch_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.aws.opensearch.OpensearchGuardiumFilter.java_class; end
end
