# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-cassandra_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::CassandraGuardiumPluginFilter < LogStash::Filters::Base
  config_name "cassandra_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.cassandra.CassandraGuardiumPluginFilter.java_class; end
end
