# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-cas***REMOVED***ndra_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::Cas***REMOVED***ndraGuardiumPluginFilter < LogStash::Filters::Base
  config_name "cas***REMOVED***ndra_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.cas***REMOVED***ndra.Cas***REMOVED***ndraGuardiumPluginFilter.java_class; end
end
