# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-azuresql_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::AzureSQLGuardiumPluginFilter < LogStash::Filters::Base
  config_name "azuresql_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.azureSQL.AzureSQLGuardiumPluginFilter.java_class; end
end
