# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-couchbasedb_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::CouchbasedbGuardiumPluginFilter < LogStash::Filters::Base
  config_name "couchbasedb_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.couchbasedb.CouchbasedbGuardiumPluginFilter.java_class; end
end
