# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-capella_guardium_filter_jars"
require "java"

class LogStash::Filters::CapellaGuardiumFilter < LogStash::Filters::Base
  config_name "capella_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.capella.CapellaGuardiumFilter.java_class; end
end
