input {
	sqs {
		queue => "guc_input_param_queue"
		access_key_id => "${GUC_CRED_ACCESS_KEY_ID}"
		region => "guc_input_param_region"
		role_arn => "guc_input_param_role-arn"
		secret_access_key => "${GUC_CRED_SECRET_ACCESS_KEY}"
		# Optional: Specify a custom endpoint (e.g., proxy)
		# endpoint => "https://proxy.company.com"
		# Set to true to use AWS's bundled CA certificates for SSL/TLS connections
		use_aws_bundled_ca => false
		# Optional: Provide additional settings (e.g., custom SSL certificate bundle)
		# additional_settings => {
		#   ssl_ca_bundle => "/usr/share/logstash/third_party/<ca_bundle_filename>"
		# }
		add_field => { "account_id" => "guc_input_param_account_id" }
		type => "guc_input_param_type"
	}
}