input{
cloudwatch_logs {

log_group => ["<LOG_GROUP>" ]  #e.g. ["/aws/docdb/"]

log_group_prefix => true  

access_key_id => <ACCESS_KEY_ID>


region => <REGION> #Non-Mandatory "ap-south-1"

codec => plain #Non-Mandatory

sincedb_path => "NUL"  #Non-Mandatory


secret_access_key => <SECRET_KEY>

event_filter => ''

#Insert the account id and cluster name of the AWS account
add_field => {"account_id" => "<ACCOUNT_ID>"}
add_field => {"cluster" => "<CLUSTER_NAME>"}

type => "docdb"
}
}
filter {
  if [type] == "docdb" {
        mutate { add_field => { "log_group" => "%{[cloudwatch_logs][log_group]}" } }
        grok { match => { "log_group" => "^/aws/docdb/%{DATA:cluster}/%{DATA:logtype}$" } }
        mutate {
            replace => { "serverHostnamePrefix" => "%{account_id}_%{cluster}" }
            replace => { "dbnamePrefix" => "%{account_id}:%{[cloudwatch_logs][log_stream]}" }
            replace => { "event_id" => "%{[cloudwatch_logs][event_id]}" }
        }
        documentdb_guardium_filter {}
    }
}
output {
stdout { codec => rubydebug }
}
