# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-azure_postgresql_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::AzurePostgresqlGuardiumPluginFilter < LogStash::Filters::Base
  config_name "azure_postgresql_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.azurepostgresql.AzurePostgresqlGuardiumPluginFilter.java_class; end
end
