# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-guardium_snowflake_filter_jars"
require "java"

class LogStash::Filters::GuardiumSnowflakeFilter < LogStash::Filters::Base
  config_name "guardium_snowflake_filter"

  def self.javaClass() Java::com.infoinsightsllc.guardium.GuardiumSnowflakeFilter.java_class; end
end
