# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-generic_guardium_filter_jars"
require "java"

class LogStash::Filters::GenericGuardiumFilter < LogStash::Filters::Base
  config_name "generic_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.generic.GenericGuardiumFilter.java_class; end
end
