# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8

require 'jar_dependencies'
require_jar('com.ibm.guardium.aws.opensearch', 'logstash-filter-opensearch_guardium_filter', '1.0.0')
