# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-teradatadb_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::TeradatadbGuardiumPluginFilter < LogStash::Filters::Base
  config_name "teradatadb_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.teradatadb.TeradatadbGuardiumPluginFilter.java_class; end
end
