# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8

require 'jar_dependencies'
require_jar('com.ibm.guardium.intersystemsiris', 'logstash-filter-intersystems_iris_guardium_filter', '0.0.18')
