# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-dynamodb_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::DynamodbGuardiumPluginFilter < LogStash::Filters::Base
  config_name "dynamodb_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.dynamodb.DynamodbGuardiumPluginFilter.java_class; end
end
