# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-s3sqs_postgresql_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::S3SQSPostgresqlGuardiumPluginFilter < LogStash::Filters::Base
  config_name "s3sqs_postgresql_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.s3sqspostgresql.S3SQSPostgresqlGuardiumPluginFilter.java_class; end
end
