input{
	beats {
		        port => guc_input_param_port
        		ssl_enabled => guc_input_param_is_ssl
        		ssl_certificate_authorities => SSL_CERT_AUTH
        		ssl_certificate => "${SSL_DIR}/tls.crt"
        		ssl_key => "${SSL_DIR}/tls.key"
        		ssl_key_passphrase => guc_input_param_passphrase
        		ssl_client_authentication => "none"
        		include_codec_tag => guc_input_param_include_codec_tag
        		type => "filebeat"
	}
}