# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-big_query_guardium_filter_jars"
require "java"

class LogStash::Filters::BigQueryGuardiumFilter < LogStash::Filters::Base
  config_name "big_query_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.bigquery.BigQueryGuardiumFilter.java_class; end
end
