# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-progress_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::ProgressGuardiumPluginFilter < LogStash::Filters::Base
  config_name "progress_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.progress.ProgressGuardiumPluginFilter.java_class; end
end
