# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-awsAuroraMysql_guardium_plugin_filter_jars"
require "java"

class LogStash::Filters::AwsAuroraMysqlGuardiumPluginFilter < LogStash::Filters::Base
  config_name "awsAuroraMysql_guardium_plugin_filter"

  def self.javaClass() Java::com.ibm.guardium.auroramysql.AwsAuroraMysqlGuardiumPluginFilter.java_class; end
end
