# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8

require 'jar_dependencies'
require_jar('com.ibm.guardium.teradatadb', 'logstash-filter-teradatadb_guardium_plugin_filter', '1.1.2')
