# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-alloydb_guardium_filter_jars"
require "java"

class LogStash::Filters::AlloyDBGuardiumFilter < LogStash::Filters::Base
  config_name "alloydb_guardium_filter"

  def self.javaClass() Java::com.ibm.guardium.alloydb.AlloyDBGuardiumFilter.java_class; end
end
